apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: rag3-aug13-1
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/maysunfaisal/rag3-aug13-1:cb6b4d5ba25b48f82f2b44f220c2fb76a7866666@sha256:64e12358242fa20a2c0deb6a9b65289d332052c4dfc5a7e0fb006f97195fec9b # use pre-built to bootstrap 
          name: app-inference
